### ISSUE TITLE
How to preprocess dataset? [VI]

### ISSUE THREAD

**Issue by NLPV2011** [DuyTa506/Wav2Vec2.0_From_Scratch#1]
Làm sao để preprocess for Pretrain(train from scratch) cho cái dataset thế ông, tôi có thể dùng data tiếng việt, trung, nhật hay hàn để làm dataset không, nếu có thì có script nào ông dùng để preprocess dataset thế ? :Đ

**Comment by DuyTa506** [comment]
Voice thì tôi cũng chỉ biết lọc nhiễu denoise, normailize độ to, chunk or split blah blah ông ạ. Trong phần Custom Dataset cũng có một số cái này rồi á .Nma thực ra tôi thấy người ta còn quan tâm đến môi trường hướng tới sử dụng mô hình để chuẩn bị data pretrain nên là bước này ít ai để ý , me too, me dumb :D 

Any way, tôi sẽ cân nhắc đến việc đưa thêm một số script để làm việc này, thanks for asking

**Comment by DuyTa506** [comment]
À về vấn đề tiếng nào tiếng nào thì có ông nhé :V như cái cách mà Meta đã từng làm để ra lò XLSR thôi ông 

https://arxiv.org/pdf/2111.09296.pdf
